import type { ThemeKey, ThemeTokens } from "./types";

const THEMES: Record<ThemeKey, ThemeTokens> = {
  forum: {
    bg: "#ffffff",
    ink: "#0a0a0a",
    muted: "#9b9b9b",
    soft: "#3a3a3a",
    line: "#ededed",
    footBg: "#0a0a0a",
    footInk: "#fafafa",
    footMuted: "#7a7a7a",
    accent: null,
    displayFamily: "'Forum', Georgia, serif",
    displayWeight: 400,
    displayLetter: "-0.022em",
    bodyFamily: "'Inter', system-ui, sans-serif",
    rowTitleSize: 56,
    ledeSize: 88,
    ledeLetter: "-0.022em",
    label: "B · Forum / warm white (original)",
  },
  "sans-stark": {
    bg: "#ffffff",
    ink: "#000000",
    muted: "#bdbdbd",
    soft: "#1a1a1a",
    line: "#000000",
    footBg: "#000000",
    footInk: "#ffffff",
    footMuted: "#7a7a7a",
    accent: null,
    displayFamily: "'Zalando Sans Expanded', 'Inter', sans-serif",
    displayWeight: 600,
    displayLetter: "-0.04em",
    bodyFamily: "'Inter', system-ui, sans-serif",
    rowTitleSize: 60,
    ledeSize: 92,
    ledeLetter: "-0.04em",
    label: "B2 · Sans-stark · Zalando Expanded, true black/white",
  },
  "bone-accent": {
    bg: "#f3efe6",
    ink: "#1a1a1a",
    muted: "#9a8f78",
    soft: "#3a3a3a",
    line: "#dcd5c4",
    footBg: "#1a1a1a",
    footInk: "#f3efe6",
    footMuted: "#9a8f78",
    accent: "#c44a2a",
    displayFamily: "'Instrument Serif', Georgia, serif",
    displayWeight: 400,
    displayLetter: "-0.018em",
    bodyFamily: "'Inter', system-ui, sans-serif",
    rowTitleSize: 56,
    ledeSize: 86,
    ledeLetter: "-0.018em",
    label: "B3 · Bone + accent · Instrument Serif, terracotta accent",
  },
};

function themeVars(themeKey: ThemeKey): string {
  const t = THEMES[themeKey];
  return [
    `--tl-bg:${t.bg}`,
    `--tl-ink:${t.ink}`,
    `--tl-muted:${t.muted}`,
    `--tl-soft:${t.soft}`,
    `--tl-line:${t.line}`,
    `--tl-foot-bg:${t.footBg}`,
    `--tl-foot-ink:${t.footInk}`,
    `--tl-foot-muted:${t.footMuted}`,
    `--tl-accent:${t.accent ?? "transparent"}`,
    `--tl-display-family:${t.displayFamily}`,
    `--tl-display-weight:${t.displayWeight}`,
    `--tl-display-letter:${t.displayLetter}`,
    `--tl-body-family:${t.bodyFamily}`,
    `--tl-row-title-size:${t.rowTitleSize}px`,
    `--tl-lede-size:${t.ledeSize}px`,
    `--tl-lede-letter:${t.ledeLetter}`,
  ].join(";");
}

export { THEMES, themeVars };
