import type { Kind } from "@/schemas/index.ts";

/** Entity kinds that currently have a canonical shader gradient preset. */
export type ShaderEntity = Exclude<Kind, "provenance">;

/** Serializable shadergradient props shared by all entity surfaces. */
export interface EntityShaderGradientPreset {
  readonly animate: "on" | "off";
  readonly axesHelper: "on" | "off";
  readonly bgColor1: string;
  readonly bgColor2: string;
  readonly brightness: number;
  readonly cAzimuthAngle: number;
  readonly cDistance: number;
  readonly cPolarAngle: number;
  readonly cameraZoom: number;
  readonly color1: string;
  readonly color2: string;
  readonly color3: string;
  readonly destination: "onCanvas";
  readonly embedMode: "on" | "off";
  readonly envPreset: "city" | "dawn" | "lobby";
  readonly format: "gif" | string;
  readonly fov: number;
  readonly frameRate: number;
  readonly gizmoHelper: "hide" | string;
  readonly grain: "on" | "off";
  readonly lightType: "3d" | "env";
  readonly pixelDensity: number;
  readonly positionX: number;
  readonly positionY: number;
  readonly positionZ: number;
  readonly range: "disabled" | "enabled" | string;
  readonly rangeEnd: number;
  readonly rangeStart: number;
  readonly reflection: number;
  readonly rotationX: number;
  readonly rotationY: number;
  readonly rotationZ: number;
  readonly shader: "defaults" | string;
  readonly type: "plane" | "sphere" | "waterPlane";
  readonly uAmplitude: number;
  readonly uDensity: number;
  readonly uFrequency: number;
  readonly uSpeed: number;
  readonly uStrength: number;
  readonly uTime: number;
  readonly wireframe: boolean;
}

/** Canonical shadergradient presets keyed by public entity kind. */
export const ENTITY_SHADER_GRADIENTS = {
  thoughts: {
    animate: "on",
    axesHelper: "off",
    bgColor1: "#000000",
    bgColor2: "#000000",
    brightness: 1,
    cAzimuthAngle: 180,
    cDistance: 2.8,
    cPolarAngle: 80,
    cameraZoom: 9.1,
    color1: "#606080",
    color2: "#8d7dca",
    color3: "#212121",
    destination: "onCanvas",
    embedMode: "off",
    envPreset: "city",
    format: "gif",
    fov: 45,
    frameRate: 10,
    gizmoHelper: "hide",
    grain: "off",
    lightType: "3d",
    pixelDensity: 1,
    positionX: 0,
    positionY: 0,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.1,
    rotationX: 50,
    rotationY: 0,
    rotationZ: -60,
    shader: "defaults",
    type: "waterPlane",
    uAmplitude: 0,
    uDensity: 1.5,
    uFrequency: 0,
    uSpeed: 0.3,
    uStrength: 1.5,
    uTime: 8,
    wireframe: false,
  },
  claims: {
    animate: "on",
    axesHelper: "off",
    bgColor1: "#000000",
    bgColor2: "#000000",
    brightness: 0.8,
    cAzimuthAngle: 270,
    cDistance: 0.5,
    cPolarAngle: 180,
    cameraZoom: 15.1,
    color1: "#73bfc4",
    color2: "#ff810a",
    color3: "#8da0ce",
    destination: "onCanvas",
    embedMode: "off",
    envPreset: "city",
    format: "gif",
    fov: 45,
    frameRate: 10,
    gizmoHelper: "hide",
    grain: "on",
    lightType: "env",
    pixelDensity: 1,
    positionX: -0.1,
    positionY: 0,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.4,
    rotationX: 0,
    rotationY: 130,
    rotationZ: 70,
    shader: "defaults",
    type: "sphere",
    uAmplitude: 3.2,
    uDensity: 0.8,
    uFrequency: 5.5,
    uSpeed: 0.3,
    uStrength: 0.3,
    uTime: 0,
    wireframe: false,
  },
  projects: {
    animate: "on",
    axesHelper: "off",
    bgColor1: "#000000",
    bgColor2: "#000000",
    brightness: 1.2,
    cAzimuthAngle: 170,
    cDistance: 4.4,
    cPolarAngle: 70,
    cameraZoom: 1,
    color1: "#94ffd1",
    color2: "#6bf5ff",
    color3: "#ffffff",
    destination: "onCanvas",
    embedMode: "off",
    envPreset: "city",
    format: "gif",
    fov: 45,
    frameRate: 10,
    gizmoHelper: "hide",
    grain: "off",
    lightType: "3d",
    pixelDensity: 1,
    positionX: 0,
    positionY: 0.9,
    positionZ: -0.3,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.1,
    rotationX: 45,
    rotationY: 0,
    rotationZ: 0,
    shader: "defaults",
    type: "waterPlane",
    uAmplitude: 0,
    uDensity: 1.2,
    uFrequency: 0,
    uSpeed: 0.2,
    uStrength: 3.4,
    uTime: 0,
    wireframe: false,
  },
  predictions: {
    animate: "on",
    axesHelper: "off",
    bgColor1: "#000000",
    bgColor2: "#000000",
    brightness: 1.5,
    cAzimuthAngle: 250,
    cDistance: 1.5,
    cPolarAngle: 140,
    cameraZoom: 12.5,
    color1: "#809bd6",
    color2: "#910aff",
    color3: "#af38ff",
    destination: "onCanvas",
    embedMode: "off",
    envPreset: "city",
    format: "gif",
    fov: 45,
    frameRate: 10,
    gizmoHelper: "hide",
    grain: "off",
    lightType: "3d",
    pixelDensity: 1,
    positionX: 0,
    positionY: 0,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.5,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 140,
    shader: "defaults",
    type: "sphere",
    uAmplitude: 7,
    uDensity: 0.8,
    uFrequency: 5.5,
    uSpeed: 0.3,
    uStrength: 0.4,
    uTime: 0,
    wireframe: false,
  },
  "changed-my-mind": {
    animate: "on",
    axesHelper: "off",
    bgColor1: "#000000",
    bgColor2: "#000000",
    brightness: 1.2,
    cAzimuthAngle: 180,
    cDistance: 3.6,
    cPolarAngle: 90,
    cameraZoom: 1,
    color1: "#ff5005",
    color2: "#dbba95",
    color3: "#d0bce1",
    destination: "onCanvas",
    embedMode: "off",
    envPreset: "city",
    format: "gif",
    fov: 45,
    frameRate: 10,
    gizmoHelper: "hide",
    grain: "on",
    lightType: "3d",
    pixelDensity: 1,
    positionX: -1.4,
    positionY: 0,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.1,
    rotationX: 0,
    rotationY: 10,
    rotationZ: 50,
    shader: "defaults",
    type: "plane",
    uAmplitude: 1,
    uDensity: 1.3,
    uFrequency: 5.5,
    uSpeed: 0.4,
    uStrength: 4,
    uTime: 0,
    wireframe: false,
  },
  decisions: {
    animate: "on",
    axesHelper: "off",
    bgColor1: "#000000",
    bgColor2: "#000000",
    brightness: 1.2,
    cAzimuthAngle: 180,
    cDistance: 2.9,
    cPolarAngle: 120,
    cameraZoom: 1,
    color1: "#ebedff",
    color2: "#f3f2f8",
    color3: "#dbf8ff",
    destination: "onCanvas",
    embedMode: "off",
    envPreset: "city",
    format: "gif",
    fov: 45,
    frameRate: 10,
    gizmoHelper: "hide",
    grain: "off",
    lightType: "3d",
    pixelDensity: 1,
    positionX: 0,
    positionY: 1.8,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.1,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -90,
    shader: "defaults",
    type: "waterPlane",
    uAmplitude: 0,
    uDensity: 1,
    uFrequency: 5.5,
    uSpeed: 0.3,
    uStrength: 3,
    uTime: 0.2,
    wireframe: false,
  },
  questions: {
    animate: "on",
    axesHelper: "on",
    bgColor1: "#000000",
    bgColor2: "#000000",
    brightness: 1.1,
    cAzimuthAngle: 180,
    cDistance: 3.9,
    cPolarAngle: 115,
    cameraZoom: 1,
    color1: "#5606ff",
    color2: "#fe8989",
    color3: "#000000",
    destination: "onCanvas",
    embedMode: "off",
    envPreset: "city",
    format: "gif",
    fov: 45,
    frameRate: 10,
    gizmoHelper: "hide",
    grain: "off",
    lightType: "3d",
    pixelDensity: 1,
    positionX: -0.5,
    positionY: 0.1,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.1,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 235,
    shader: "defaults",
    type: "waterPlane",
    uAmplitude: 0,
    uDensity: 1.1,
    uFrequency: 5.5,
    uSpeed: 0.1,
    uStrength: 2.4,
    uTime: 0.2,
    wireframe: false,
  },
  posts: {
    animate: "on",
    axesHelper: "on",
    bgColor1: "#000000",
    bgColor2: "#000000",
    brightness: 1.1,
    cAzimuthAngle: 0,
    cDistance: 7.1,
    cPolarAngle: 140,
    cameraZoom: 17.3,
    color1: "#ffffff",
    color2: "#ffbb00",
    color3: "#0700ff",
    destination: "onCanvas",
    embedMode: "off",
    envPreset: "city",
    format: "gif",
    fov: 45,
    frameRate: 10,
    gizmoHelper: "hide",
    grain: "off",
    lightType: "3d",
    pixelDensity: 1,
    positionX: 0,
    positionY: 0,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.1,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    shader: "defaults",
    type: "sphere",
    uAmplitude: 1.4,
    uDensity: 1.1,
    uFrequency: 5.5,
    uSpeed: 0.1,
    uStrength: 1,
    uTime: 0,
    wireframe: false,
  },
  inputs: {
    animate: "on",
    axesHelper: "on",
    bgColor1: "#000000",
    bgColor2: "#000000",
    brightness: 1.1,
    cAzimuthAngle: -22,
    cDistance: 7.1,
    cPolarAngle: 133,
    cameraZoom: 2.79,
    color1: "#ffffff",
    color2: "#e3c7ff",
    color3: "#0015ff",
    destination: "onCanvas",
    embedMode: "off",
    envPreset: "city",
    format: "gif",
    fov: 45,
    frameRate: 10,
    gizmoHelper: "hide",
    grain: "off",
    lightType: "3d",
    pixelDensity: 1,
    positionX: 0,
    positionY: 0,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.1,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    shader: "defaults",
    type: "sphere",
    uAmplitude: 1.4,
    uDensity: 1.1,
    uFrequency: 5.5,
    uSpeed: 0.1,
    uStrength: 1,
    uTime: 0,
    wireframe: false,
  },
} as const satisfies Record<ShaderEntity, EntityShaderGradientPreset>;

/** Returns whether a public entity kind has a canonical shader gradient preset. */
export function hasEntityShaderGradient(entity: string): entity is ShaderEntity {
  return Object.hasOwn(ENTITY_SHADER_GRADIENTS, entity);
}
